select 
TRY_CAST(DATES AS DATE) as DATES,
SALESPERSON,
CUSTOMERNAME,
CARMAKE,
CARMODEL,
TRY_CAST(CARYEAR AS NUMBER) as CARYEAR,
SALEPRICE, COMMISSIONRATE AS COMRATE, COMMISSIONEARNED AS  COMEARNED
from {{ source('raw_bi_car', 'CAR_SALES') }}
where TRY_CAST(DATES AS DATE) > '2020-01-01'